# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Bonjour"
url = "https://bonjour.bio/libra"
[main.params]
icon = "tag"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Octl1bra"

[social.params]
icon = "brand-github"

[[social]]
identifier = "rss"
name = "RSS"
url = "https://libra.wiki/post/index.xml"

[social.params]
icon = "rss"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:me@libra.wiki"

[social.params]
icon = "mail"